In [1]:
import sqlite3
import pandas as pd

# Connect SQLite database
conn = sqlite3.connect("superstore.db")

In [2]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

Empty DataFrame
Columns: [name]
Index: []

In [3]:
pd.read_sql_query(
    "PRAGMA table_info(orders);",
    conn
)

Empty DataFrame
Columns: [cid, name, type, notnull, dflt_value, pk]
Index: []

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("superstore.db")

In [13]:
df = pd.read_csv(r"C:\Users\shokd\Desktop\Superstore\sales-revenue-intelligence\data\train.csv")

In [14]:
df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

9800

In [15]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

    name
0  sales

In [16]:
pd.read_sql_query(
    "PRAGMA table_info(sales);",
    conn
)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code     REAL        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0

In [17]:
query = """
SELECT
    STRFTIME('%Y', "Order Date") AS order_year,

    ROUND(SUM("Sales"), 2) AS total_revenue,

    ROUND(
        (
            SUM("Sales") -
            LAG(SUM("Sales")) OVER (
                ORDER BY STRFTIME('%Y', "Order Date")
            )
        ) * 100.0 /

        LAG(SUM("Sales")) OVER (
            ORDER BY STRFTIME('%Y', "Order Date")
        ),
        2
    ) AS yoy_growth_pct

FROM sales

GROUP BY STRFTIME('%Y', "Order Date")

ORDER BY order_year;
"""

result = pd.read_sql_query(query, conn)

result

  order_year  total_revenue yoy_growth_pct
0       None     2261536.78           None

In [18]:
pd.read_sql_query(
    '''
    SELECT "Order Date"
    FROM sales
    LIMIT 5;
    ''',
    conn
)

   Order Date
0  08/11/2017
1  08/11/2017
2  12/06/2017
3  11/10/2016
4  11/10/2016

In [19]:
query = """
SELECT
    SUBSTR("Order Date", -4) AS order_year,

    ROUND(SUM("Sales"), 2) AS total_revenue,

    ROUND(
        (
            SUM("Sales") -
            LAG(SUM("Sales")) OVER (
                ORDER BY SUBSTR("Order Date", -4)
            )
        ) * 100.0 /

        LAG(SUM("Sales")) OVER (
            ORDER BY SUBSTR("Order Date", -4)
        ),
        2
    ) AS yoy_growth_pct

FROM sales

GROUP BY SUBSTR("Order Date", -4)

ORDER BY order_year;
"""

result = pd.read_sql_query(query, conn)

result

  order_year  total_revenue  yoy_growth_pct
0       2015      479856.21             NaN
1       2016      459436.01           -4.26
2       2017      600192.55           30.64
3       2018      722052.02           20.30

In [20]:
query = """
SELECT

    SUBSTR("Order Date", 4, 2) AS order_month,

    ROUND(SUM("Sales"), 2) AS monthly_revenue

FROM sales

GROUP BY order_month

ORDER BY order_month;
"""

monthly_sales = pd.read_sql_query(query, conn)

monthly_sales

   order_month  monthly_revenue
0           01         94291.63
1           02         59371.12
2           03        197573.59
3           04        136283.00
4           05        154086.72
5           06        145837.52
6           07        145535.69
7           08        157315.93
8           09        300103.41
9           10        199496.29
10          11        350161.71
11          12        321480.17

In [21]:
query = """
SELECT
    "Region",
    ROUND(SUM("Sales"), 2) AS total_revenue
FROM sales
GROUP BY "Region"
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, conn)

result

    Region  total_revenue
0     West      710219.68
1     East      669518.73
2  Central      492646.91
3    South      389151.46

In [22]:
query = """
SELECT
    "Product Name",
    ROUND(SUM("Sales"), 2) AS total_sales
FROM sales
GROUP BY "Product Name"
ORDER BY total_sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

                                        Product Name  total_sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System     19024.50
6               Hewlett Packard LaserJet 3310 Copier     18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...     18374.90
8          GBC DocuBind P400 Electric Binding System     17965.07
9        High Speed Automatic Electric Letter Opener     17030.31

In [23]:
query = """
SELECT
    "Category",
    ROUND(SUM("Sales"), 2) AS total_sales
FROM sales
GROUP BY "Category"
ORDER BY total_sales DESC;
"""

result = pd.read_sql_query(query, conn)

result

          Category  total_sales
0       Technology    827455.87
1        Furniture    728658.58
2  Office Supplies    705422.33

In [24]:
query = """
SELECT
    "State",
    ROUND(SUM("Sales"), 2) AS total_revenue
FROM sales
GROUP BY "State"
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

          State  total_revenue
0    California      446306.46
1      New York      306361.15
2         Texas      168572.53
3    Washington      135206.85
4  Pennsylvania      116276.65
5       Florida       88436.53
6      Illinois       79236.52
7      Michigan       76136.07
8          Ohio       75130.35
9      Virginia       70636.72

In [25]:
query = """
SELECT
    "Customer Name",
    ROUND(SUM("Sales"), 2) AS customer_revenue
FROM sales
GROUP BY "Customer Name"
ORDER BY customer_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

        Customer Name  customer_revenue
0         Sean Miller          25043.05
1        Tamara Chand          19052.22
2        Raymond Buch          15117.34
3        Tom Ashbrook          14595.62
4       Adrian Barton          14473.57
5        Ken Lonsdale          14175.23
6        Sanjit Chand          14142.33
7        Hunter Lopez          12873.30
8        Sanjit Engle          12209.44
9  Christopher Conant          12129.07